name: aptible

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Aptible
      run: aptible deploy --app aptible --git-commitish=main
      env:
         APTIBLE_DEPLOY_TOKEN: $ {{ secrets.APTIBLE_DEPLOY_TOKEN }}
